### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/merkle-tree#37]
- [ ] Support for bytes32 leaves
- [ ] Support for custom internal hash
- [ ] Linting
- [ ] Non regression tests.

**Comment by LayneHaber** [comment]
curious if we can get an rc for the `SimpleMerkleTree`?
